### ISSUE TITLE
Layer List / Legend - display each layer's legend piece under the respective layer

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#10]
Right now you get the entire legend a the top under  "master" map service.  What would be ideal would be to have each layer have its own piece of the legend under it.

**Comment by shodge17** [comment]
Lets go ahead and switch back to the layer list AND legend buttons rather than the configuration you tried.    See if you can just comment and comment out what you have now so we can come back to it later and try to get it like we want it.

**Comment by clintonlunn** [comment]
This has been swapped out. Layerlist legend is gone, separate layers and legend menu items were put back in.
