### ISSUE TITLE
scrolling is disabled after clicking on layerlist

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#101]
after clicking on a layerlist, scrolling becomes disabled

**Comment by clintonlunn** [comment]
I cannot reproduce this behavior

**Comment by PhilipGriffith** [comment]
Is this still an issue? It says you moved it Done in the project. Maybe the issues and the project cards aren't synced?

**Comment by clintonlunn** [comment]
Yes, I would mark this as done. I was never able to reproduce this case again after the demo with Lamar.
