### ISSUE TITLE
Lock Layerlist panel header

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#108]
This happens if multiple layers are opened within the Layerlist panel:
![image](https://user-images.githubusercontent.com/14999738/56767181-1145c680-6779-11e9-91f4-021388c6d264.png)

If you scroll down the panel, the header scrolls, too:
![image](https://user-images.githubusercontent.com/14999738/56767373-929d5900-6779-11e9-9de5-82f78228800e.png)

Is there a way to "lock" this so that the header stays in place while everything else scrolls?

**Comment by clintonlunn** [comment]
Sure thing, I'll get right on this.

**Comment by clintonlunn** [comment]
I was able to sticky both of the layerlist and legend headers. I'll create a pull request so we can review these changes more. 
@PhilipGriffith
