### ISSUE TITLE
Zoom to a coordinate

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#11]
This is a very low priority so if it doesn't get done - no big deal.   Ideally  this would all the user to enter state plane coordinates (and zone) or lat / lon (decimal degrees and degree / minutes / seconds)

**Comment by clintonlunn** [comment]
The user is able to zoom to a lat-lon position, but not any other type of coordinates.

**Comment by clintonlunn** [comment]
this functionality has been made possible in the coordinates widget
