### ISSUE TITLE
Certified Corner Labels No Longer Display?

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#120]
As a preface, this is most likely my fault, but also hopefully an easy fix. In attempting to use the LABINS_Data service for other purposes, I republished it with labels turned on for the Certified Corners (ID: 2) layer. We ended up moving the functionality we needed to a separate service, and so I republished the entire LABINS_Data service, only this time with the labels turned off for that same layer.

Before the change, the label button next to the Certified Corners layer in the Layerlist of LABINS worked correctly. After republishing the layer (with presumably the exact same settings?), it no longer applies the labels, instead throwing `TypeError: targetLayer is undefined`.

Any idea what's going on?

**Comment by clintonlunn** [comment]
Ouch, I'll start researching this.

**Comment by clintonlunn** [comment]
I think you may have overlooked something. The LABINS data is not failing, it's the Coastal Construction Control Lines, which is not hosted by us. Not sure why this has just now stopped working. 

![image](https://user-images.githubusercontent.com/24685932/73110742-86475780-3ed5-11ea-92eb-f0e5b8d62bc3.png)

**Comment by clintonlunn** [comment]
http://ca.dep.state.fl.us/arcgis/rest/services/OpenData/COASTAL_ENV_PERM

url was changed. their online map is not working either. 

https://floridadep.gov/rcp/coastal-construction-control-line/content/locate-coastal-construction-control-line-cccl

**Comment by PhilipGriffith** [comment]
Well that was an easy fix! :)

**Comment by clintonlunn** [comment]
I guess they republished that layer too at roughly the same time As @PhilipGriffith did. What a coincidence

**Comment by PhilipGriffith** [comment]
I was actually out with the GIS manager of DEP on Saturday. They were upgrading all of their systems on Friday, so _none_ of their services would have been working. I totally missed that possibility. lol Good eye!
