### ISSUE TITLE
Never zoom to feature on an identify

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#121]
There seem to be too many times when I just want to identify something and slightly miss and the map zooms to some large polygon feature.  I think I want ALL zooms like this stopped no matter what the feature is.

**Comment by clintonlunn** [comment]
I can get this taken care of today.

**Comment by clintonlunn** [comment]
I made a PR with these changes at https://github.com/FREAC/LABINS/pull/124. There are a lot of things depending on the highlight and feature zoom functionality, but hopefully I didn't miss anything!

**Comment by shodge17** [comment]
I just tested this in a bunch of different areas and ways.  I think it is working like we want it to

**Comment by clintonlunn** [comment]
Great! Will this be merged into the development branch or the master branch??

**Comment by shodge17** [comment]
Dev

**Comment by clintonlunn** [comment]
Alright, merged!
