### ISSUE TITLE
Upgrade to version 4.15 of API

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#128]
We need to upgrade to the latest version of the API so that we can upgrade to the swipe issue (issue #127).

Order of events needed:
- branch off of enhancements 
- upgrade to latest api version and test
- merge back into enhancements

**Comment by clintonlunn** [comment]
There's a major bug that's been introduced somewhere. the Data Query panel is broken. Trying to track it down. Gotta solve it before we go any further with this branch I think.

**Comment by clintonlunn** [comment]
There's a whole slew of bugs that have been introduced somehow. I am guessing they're all inter-related. I'm trying to nail down the cause but we've introduced some breaking changes somewhere between our code in production and our code that's both currently in the mater branch and in the enhancements branch.

**Comment by PhilipGriffith** [comment]
The code in `master` is currently running v4.15. The major change I saw was with the search widget source layers (thanks for fixing that!), but many of the other bugs seem to have been either fixed or have disappeared after other, unrelated, code changes.
