### ISSUE TITLE
Need a query option

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#13]
This option is where you can specify a layer to search on (eg NGS) and field to search on (eg county).  Upon  execution, the query creates a popup of all NGS records that meet that criteria.  if you click on one the map zooms to that point

**Comment by clintonlunn** [comment]
The data query functionality from the current Flex LABINS map has been replicated except for selection of township-range-section. However, this data query functionality can be found within the zoom to feature menu panel.
