### ISSUE TITLE
Set the section to null when a township/range has been selected

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#131]
Currently, the dropdowns for County, City, and Quad on the Zoom to Feature panel are not aware when the user selects the Township/Range/Section dropdowns. The graphic is removed, but the dropdowns are reset. 

Behavior should include:
- Given that  County, City, or Quad on the Zoom to Feature panel has something other than the default value in it
- And the user clicks on the Township/Range/Section area of the Zoom to Feature Panel
- Then the County, City, Quad dropdowns should all reset to their default values.

**Comment by shodge17** [comment]
I am not sure if this is related to any fixes you have done, but watch what happens on a straight T/R/S query
1) select a township
2) select a range (map correctly zooms to the correct T/R combination)
3) note that section 01 is displayed in the section piece
4) if you want to go to section 01 by picking it  nothing happens
5) if you pick another section it works correctly
After a range is selected the section should remain blank.  You may just need to add a "blank" option to the list.

**Comment by shodge17** [comment]
the original problem with this ticket has been fixed.  Just the comment above needs to be implemented.

**Comment by clintonlunn** [comment]
Since the original issue regarding this is fixed, I am going to close this and open another issue with these new details.

**Comment by clintonlunn** [comment]
See issue #193
