### ISSUE TITLE
Function scope of goToFeature on infoPanelData variable

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#133]
This is more of a question than anything: Stephen has noticed that if you click on a point, an action which then triggers the `goToFeature` function, the `goTo` target is described as `infoPanelData[0].geometry`, whereas that variable seems to be a global variable, as it isn't defined within the scope of the function. (Incidentally, in the comments I see that you have this listed as a TODO and mention that it isn't working correctly.) When `infoPanelData[0]` is changed to `feature`, which _is_ within the function scope, this problem goes away.

Here's the question: do you have reason to believe this change will break the code elsewhere? Or is it a change that could be made permanent?

Thanks!

P.S.
I "assigned" this to you, but just to make sure you saw it. Once we get your thoughts, either Stephen or I can take care of it. :)

**Comment by clintonlunn** [comment]
Wow, thanks for pointing this out. I don't know how I missed this. I changed it in my upgrade to [4.14 branch](https://github.com/FREAC/LABINS/commits/version-upgrade-4_14) for testing purposes to see if it broke anything else.

**Comment by PhilipGriffith** [comment]
This is both fixed and not fixed in the current code, so I'm going to close this issue. lol
