### ISSUE TITLE
Finalizing new CCR layer InfoPanel data

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#135]
Some time ago, Clinton developed logic for building CCR links to the LABINS FTP site using the Related table within the base_and_survey database. Those results are currently added to the information panel outside of the **Certified Corners** section on the Info panel:
![image](https://user-images.githubusercontent.com/14999738/80511928-c7269080-894a-11ea-8ec7-48512311a47f.png)
I would like to switch out the code used to build the links in the official section with the new, dynamically generated code. When I do, should I also remove the links to the TIF images? Or should they be left?

**Comment by shodge17** [comment]
1) yes replace the lower pdfs with the ones from the relationship
2) for now at least lets leave the tifs in there so I can do some extensive testing 
3) you need to get Georgianna to give you the most up-to-date CCR file.  It may be there already, just get her to tell you the latest docnum and then you can check some of the ccr files loaded to the .182 db.
4) you will need to create a new relationship class 

On the branch this code is in, does a single click on a blank space on the map cause the map to recenter to the township or quad and adjust the zoom factor.  there is a branch that does NOT recenter and zoom.  We do not want the recenter and zoom.  it can highlight, but dont zoom or recenter.  just call me if you have a question about this.

**Comment by PhilipGriffith** [comment]
Of course, there's a snag. Currently, the Certified Corner Records are within a MapImageLayer.
However, MapImageLayer's don't support Related Queries.
I see two ways forward:
1. Use another service, hosted as a FeatureLayer (which _does_ support Related Queries), _in addition to_ the one being currently used in the MapImageLayer. Problems with this approach include yet more duplicate data, as well as needing to update both layers in order to make sure they are in sync with one another.
2. Host the Certified Corner Records as a FeatureLayer in its own service and rewrite some of the code that currently fills the "Data Query" panel. This will involve a bit more work at the start, but will mean the data only exists in one place, so when we update it, we're done.

Either way, it looks like we'll need to create another service to host the new feature layer.

**Comment by PhilipGriffith** [comment]
Hold that thought. I may be overthinking this.

**Comment by shodge17** [comment]
if you want to talk about this, call me tomorrow

**Comment by shodge17** [comment]
All of this got rolled into issue 119.  Going to close this one.
