### ISSUE TITLE
production map does not complete identifytask on mobileview

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#136]
production map will not complete identifytask on mobile view. we receive the following console error in mobile view indicating that coordExpand is not defined:

![image](https://user-images.githubusercontent.com/24685932/81027812-1a1dad80-8e4d-11ea-869d-a207dc45568d.png)

![image](https://user-images.githubusercontent.com/24685932/81027826-2570d900-8e4d-11ea-81ab-30d323d0470e.png)

This console error traces back to this piece of code: 
![image](https://user-images.githubusercontent.com/24685932/81027860-45080180-8e4d-11ea-9766-0841fe2d5f5c.png)

**Comment by clintonlunn** [comment]
coordExpand wasn't defined in mobile view (because we don't expose the coordinate widget in mobile view) so i added some logic to cover that scenario. We want to keep the requirement that a user cannot initiate an identifytask if > minimum drawing distance or the coordinate expand widget is expanded.

However, because coordExpand is not defined in mobile view, we don't need to check if it isn't expanded, instead we can just add a flag that the user is on mobile.

**Comment by shodge17** [comment]
Thank you Clinton.  Fast fix!
