### ISSUE TITLE
Cleaning up the branches

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#139]
Below is a screenshot of the currently open branches:
![image](https://user-images.githubusercontent.com/14999738/81189241-60c1f380-8f84-11ea-9cf5-886f85e64057.png)

Here's my question: Which branches can be merged into master or removed?
Specifically:
1. Of the two stale DEP branches, which one _actually_ provides access for the DEP members? I'll remove the other one. (I'd be very curious to see if this has ever been accessed in the past year, but that's another question.)
2. What is the difference between `version-upgrade-4_14` and `version-upgrade`?
3. What is the difference between the `enhancements` branch and the upgrade branches?
4. When I complete the new logic for the CCR layer and merge it into `master`, can I then also remove the `new-ccr-layer` branch?

Thanks!

**Comment by clintonlunn** [comment]
1. version-upgrade can be deleted.
2. the version-upgrade-4_14 is a branch that I'm actively working on to upgrade to 4.15 (started upgrading when it was 4.14, but 4.15 was released last month) version of the api 
3. the enhancements branch is the release branch that i've been merging different features into. 
4. that logic might want to also get added to the enhancements branch

**Comment by PhilipGriffith** [comment]
Alle ist klar! I've created a `tester` branch that will allow us to test any code changes before pushing them to the master and will integrate any changes to the CCR logic there, so you'll be able to pull from either `tester` or `master` when it's all finally done.

**Comment by PhilipGriffith** [comment]
Looking at the code for the two branches, it looks like `dep-duplicate-map` was an initial branch, then `dep-access` integrated more up-to-date code changes. Does that sound correct? I'm going to test each, and if `dep-access` does everything it's intended to do, I plan to remove the `dep-duplicate-map` as redundant. If I remember correctly, `dep-access` should look much like master, but also display **MHW** in the Information Panel. Is that right?

**Comment by PhilipGriffith** [comment]
Done! Once the version upgrade and new CCR layer is integrated, those two branches will go the way of the dodo as well. :)
