### ISSUE TITLE
Remove the Data Query panel

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#145]
I'm seriously considering removing the Data Query panel altogether.
Here are my reasons:
1. It's next to useless in terms of the amount of data you get back. There is functionally no difference between stuffing 1000 records into the info panel and simply listing every single possible record in the dataset: with no other form of searching on the records you've selected, you are scrolling through a haystack looking for a needle.
2. It creates a huge headache when adding third-party layers, as the dropdown menus are closely related to the dropdown boxes created for querying the information.
3. The Search widget already does what we want the Data Query panel to be doing (especially with autocomplete on the data layers), but with much less screen real estate.

**Comment by clintonlunn** [comment]
I wish there was some way for us to tell if it is actually being used.

**Comment by PhilipGriffith** [comment]
We remove it and see if anyone calls. lol

**Comment by shodge17** [comment]
Lets close this.  If it presents a issues in the future we can reconsider getting rid of it.
