### ISSUE TITLE
Quad number is incorrect on drill-down identify

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#149]
> Lamar forwarded this message to me and I have answered the gentleman.  I believe he is saying that for his particular spot in Eustis, fl the old labins map gives him a quad number of 3914 and the new labins map gives him a different number that does have a corresponding file in the FTP site.  I checked with the Geographic Profile, and the part of Eustis he is referring to is in fact in quad 3914.
Clinton, can you check that you are using the correct quad file, or possibly you could be printing a different field?  
Thank you!
Georgianna

Lamar has reported that there is an issue with the Quad Number field when performing an drill-down identify with quad visibility enabled. 

There is a conflict between the original labins map and the updated LABINS map where the attribute field that we are using as the Quad Number is incorrect. The original LABINS map is what is known to be the source of truth for this issue.

For example: 

![image](https://user-images.githubusercontent.com/24685932/94346370-3ee01080-fffa-11ea-969e-9242f8173700.png)

However looking at the old Labins site it tells me the quad number is 3914
![image](https://user-images.githubusercontent.com/24685932/94346374-499aa580-fffa-11ea-9b91-daefcf21ce7f.png)

From this metafile directory: `https://ftp.labins.org/DRG2/StPl/EAST/ `, where I have always gotten DRG quad maps for Florida State Plane East, the quad map 3914 exists but the quad map 2446 does not exist.
![image](https://user-images.githubusercontent.com/24685932/94346394-6b942800-fffa-11ea-8fda-171d490998a8.png)

![image](https://user-images.githubusercontent.com/24685932/94346398-6e8f1880-fffa-11ea-9246-fa0c475a5a35.png)

**Comment by clintonlunn** [comment]
This issue was caused by us referencing `q_902_83_i` instead of the `wmd_` field. See example below:

[`Query Example`](https://maps.freac.fsu.edu/arcgis/rest/services/LABINS/LABINS_Data/MapServer/8/query?where=tile_name+%3D+%27EUSTIS%27&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=false&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=html)

![image](https://user-images.githubusercontent.com/24685932/94346490-f9701300-fffa-11ea-8fc6-e023c4acf7e0.png)

**Comment by clintonlunn** [comment]
I opened a PR for the master branch based on the workflow of merging feature to master, then master to production.

**Comment by shodge17** [comment]
This is working like it should
