### ISSUE TITLE
Top Search Bar

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#15]
Dont close the the search window when the user pushes the search button.

**Comment by PhilipGriffith** [comment]
Which search button do you mean?

**Comment by clintonlunn** [comment]
I think this is meant to be the search widget. When you enter in a search
term, it collapses the search bar once you press the search button.

**Comment by PhilipGriffith** [comment]
One issue with this request is that the application is no longer mobile-friendly, at least aesthetically speaking:
![image](https://user-images.githubusercontent.com/14999738/40660659-a7e51e42-631f-11e8-98b1-4f5afa0ec63b.png)
