### ISSUE TITLE
error message thrown when typing in search bar

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#152]
Error message being trown: invalid-field: outField is invalid

![image](https://user-images.githubusercontent.com/24685932/94353113-4247bc00-003b-11eb-9793-97bc53b50f16.png)

Production branch also throws this error and error message and it is fixed when commenting out the Erosion Control Lines layer. This is being caused by an incorrect reference to the Erosion Control Lines layer. It should be referencing url: `labinsURL + '7'`

![image](https://user-images.githubusercontent.com/24685932/94353503-c8660180-003f-11eb-84f3-0ad206c198b4.png)

**Comment by clintonlunn** [comment]
Did some more investigation and realized that this has been corrected in the master branch. Once those changes are merged into production, the issue will be fixed.

**Comment by shodge17** [comment]
I  think we can close this.  If you agree, go ahead and close it.

**Comment by clintonlunn** [comment]
You're right, it's fixed in master branch.
