### ISSUE TITLE
Tide interpolation points

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#153]
Production works correctly of tide interpolation points -- IE we do not show them any values
try this on production
1) data zoom
2) tide interpolation points
3) county = Wakulla
4) click on the point labeled 10002
5) Note what the page looks like when you click the "here" link.
Now repeat that with the master branch.  See that the here link gives you a form with values.  that is NOT right.  We do not want to show the user any values.  I think you just need to comment out or delete the code from line 111 to 119 and add line 106 found in production.

This makes me a bit nervous.  Production looks good for Tide Interpolation points but Master has the original way that we got rid of at least a year or two ago.

**Comment by clintonlunn** [comment]
i reverted back to what is in production

**Comment by clintonlunn** [comment]
merged into master
