### ISSUE TITLE
Auto expand the coordinate measurement systems when coordinate conversion widget is opened

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#166]
Expand the default conversion widget to full size when user opens the widget.

~Add feet- and meter-based coordinate systems for FL state plane N, E, W.~ <-- Will not fix unless it becomes an issue

**Comment by shodge17** [comment]
This code will allow the widget to open and display all the preloaded systems.
  ccWidget._expanded = true;

There doesn't seem to be an EPSGs for state plane meters so for now lets close this ticket after the minor update above is put in place.  We can deal with meters when someone asks about it.  The zones are scheduled to be revised in the next year or two so I think we will be good for awhile.
