### ISSUE TITLE
Layer toggle swipe

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#169]
·         Implement a swipe widget to swipe all layers on/off.

**Comment by shodge17** [comment]
Here are the layers we will want to see in the swipe tool to start with
[labinsLayer,  ngsLayer, swfwmdLayer, CCCLLayer]
NOTE: you need to strategically place the swipe widget at least after the layerList is created near line 1097 in script.js

**Comment by shodge17** [comment]
closing this because 127 has everything in it.
