### ISSUE TITLE
enable minimizing of overview map

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#170]
·         Refactor the overview map to allow minimization of the overview map when users do not want to see it.

**Comment by clintonlunn** [comment]
@GeorgiannaS @shodge17, we could also toggle the overviewMap off/on when the measurement widgets are active/inactive. With a smaller screen, the measurement widget overlaps other buttons/widgets. Putting overviewMap into right bottom corner would give the most space I think.

**Comment by shodge17** [comment]
Currently the overview map does not show on my phone or my tablet when using the real LABINS map from the website.  I think that is the right thing to do.

So what I do not see yet is the ability to minimize the overview map on the desktop.  Is that something you are still working on?  This would be a low priority

**Comment by clintonlunn** [comment]
@shodge17 are you looking in branch [#170/toggle-overview-map](https://github.com/FREAC/LABINS/tree/%23170/toggle-overview-map)?

I added a button to the navbar that does the toggle action.

![image](https://user-images.githubusercontent.com/24685932/104205037-ec393180-53fb-11eb-971d-72c5ba7c193a.png)

**Comment by shodge17** [comment]
Ahh..  I was just looking on the overview itself.  this looks fine with me.  I see there isnt a built in option so I am fine with this solution.  
So is the  pull ready with this option?  its been there awhile -- I just didnt have time to review it.

**Comment by clintonlunn** [comment]
The changes look good to me. Before it goes to the live website, let's let it sit in the master branch so we can test it with the rest of the code first at [the demo site](https://freac.github.io/LABINS/)

**Comment by clintonlunn** [comment]
After checking on this in the demo site. This change looks good. All looks good on both phone and computer!

However, I think it would be worth it in the future to prevent the overviewMap from loading at all on mobile devices. Doing so would increase the performance of the overall website (on mobile devices) I think. I created issue #185 to address it.
