### ISSUE TITLE
Update to latest JSAPI version

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#171]
Upgrade to the latest version of the JavaScript API (4.17 at the time of creating this issue) (This is necessary for the swipe widget and other future enhancements.)

**Comment by shodge17** [comment]
I know the 3 commented out lines needs to happen.  It does not look like they are used.  I think they were used at one point but the strategy changed over time.  Left in, they break at 4.17.  So far I do not see any ramifications for them being commented out.
![image](https://user-images.githubusercontent.com/10946159/104751463-67b02100-5723-11eb-9331-f799c4cf26a6.png)

**Comment by clintonlunn** [comment]
I think Philip made that renderer code so I am not very familiar with the thought process that went behind it. I am testing the update to 4.18 and am not finding any issues so far. However, I am testing after 10PM, which is when some of the services go offline. I'll have to come back when all of the services are available to get some full testing done. From what I can tell though, commenting out those lines in the custom rendered only produces positive results

**Comment by clintonlunn** [comment]
I cannot find anything wrong with the map after that renderer code is removed. We should continue to do testing on once merged into master and accessible on http://freac.github.io/LABINS/#
