### ISSUE TITLE
Quad name search enhancement

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#172]
Implement a method to search points by Quad Names containing three words (i.e. “Big Mossy Head”).

**Comment by clintonlunn** [comment]
@shodge17 Could I get a few more details on this issue? 

Is this issue just asking to add quad name search functionality? Currently, we don't have any way to search by USGS Quad name, so I just implemented the ability to search by Quad name via the search bar and the data query panel.

Is this the intended outcome for this enhancement?

**Comment by shodge17** [comment]
I am not sure why this is here.  The zoom to feature DOES allow you to select a particular quad.  If you agree, close this.

**Comment by clintonlunn** [comment]
@shodge17  for why this is here, this came from the list of requirements for the new LABINS map update. however, you are correct it does currently have comparable functionality in the zoom to feature panel. 

i added some additional ways to get at a particular name though through the branch i created for this issue (through the search bar and data query panel). i'm going to close this for now though since it sounds like this wasn't intentionally asked for.

**Comment by clintonlunn** [comment]
@shodge17 I think you opened the wrong issue. You're looking for #167. I've reopened that one.
