### ISSUE TITLE
disable measurement toolbar for mobile version

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#178]
related to #167, the measrurement toolbar doesn't work well on mobile. for now, we need to remove it

**Comment by shodge17** [comment]
Unfortunately this update breaks the identify tool.  Not sure why but if you comment out the if (screen.availWidth > 992) line then things work again.

**Comment by clintonlunn** [comment]
on it, thanks for the heads up

**Comment by clintonlunn** [comment]
#181 PR reverts this change until i can come up with a fix that doesn't break identify
