### ISSUE TITLE
prevent overView map from loading when on mobile

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#185]
Currently the overview map loads on both mobile and non-mobile devices. Non mobile (i.e. regular laptops or desktop computers) devices load the overviewmap just fine. However, on mobile devices the overview map is still loaded, but hidden to prevent the user from accessing it. 

I propose removing the overview map from even loading on mobile devices. Slimming down the widgets used would certainly yield some performance gains. How much exactly is hard to say though.

**Comment by clintonlunn** [comment]
@shodge17 what do you think about putting this in the 2021 update project?

**Comment by shodge17** [comment]
I am fine with that.
