### ISSUE TITLE
Update the About page

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#187]
Get rid of this sentence on the about (info) page accessible via the map menu

"This is the updated LABINS Data Explorer created to replace the current LABINS Viewer in Flex which can be found here."

**Comment by clintonlunn** [comment]
![image](https://user-images.githubusercontent.com/24685932/104536334-e69f3f80-55e5-11eb-9e6f-c8b9c03b878c.png)
Previous state of about page for reference.

**Comment by clintonlunn** [comment]
![image](https://user-images.githubusercontent.com/24685932/104537388-e3a54e80-55e7-11eb-843a-2d3ea13bef52.png)

After edit
