### ISSUE TITLE
Prevent coordinate conversion widget from loading on mobile

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#192]
Currently, if a user is on a mobile device, the coordinate conversion widget loads but is not visible. I propose that we refactor the code so that the widget does not try to load at all on a mobile device. This would lead to a performance gain while on mobile devices.

**Comment by clintonlunn** [comment]
@shodge17 what do you think about puting this into the [2021 update](https://github.com/FREAC/LABINS/projects/2)project?

**Comment by shodge17** [comment]
This looks like you got this fixed already.  Agreed?

**Comment by clintonlunn** [comment]
No this hasn't been done yet, I'll get a PR ready to complete this.
