### ISSUE TITLE
Section auto sets to an unexpected value when TRS selection made then user selects another value (city/quad/etc)

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#193]
1. select a township
2. select a range (map correctly zooms to the correct T/R combination)
3. note that section 01 is displayed in the section piece
4. if you want to go to section 01 by picking it nothing happens
5. if you pick another section it works correctly
6. if you pick, say, a city to zoom to after a successful T/R/S zoom the section number defaults to 01
7. After a range is selected the section should remain blank. You may just need to add a "blank" option to the list.

https://user-images.githubusercontent.com/24685932/104831945-4a7e6e00-585b-11eb-83aa-26577eb1b1db.mov

**Comment by shodge17** [comment]
FIX: Find the buildSectionDropdown fuction
after the sectionIntArr is built and before it it sorted add this line:     sectionIntArr.push('')
