### ISSUE TITLE
CCR relate update caused the certified corner zoom to break

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#197]
Old way of symbolizing the PLS layer was using the field is_image.  This was set to "Y" with one of Georgianna's update programs.  We no longer run that program so all new PLS corners that get documented will have is_image set to "N" even though there is a document for it.

SOLUTION:  in the ArcMap project JOIN (Not relate like you might think because there is a 1 to many relationship) the pls_ptp_master_3857 to the ccr_master table.  We don't care if there is one or 50 ccr records associated with a corner, so long as there is one then code the point as a black circle otherwise its an open circle.  You can't symbolize a layer using relate fields (or at least you can't easily do it).

Because we now have a JOIN the attributes are all referenced with a fully qualified name unlike before when the attribute name was just the attribute name,  EXAMPLE (and the problem): "blmid" is now "base_and_survey.sde.pls_ptp_master_3857.blmid".  NOTE: both the pls_ptp_master_3857 table and the ccr_master table have a field named "blmid".  If the search field had been unique this MAY not have been a problem.

FIX: find the place where this query is built and change the field name (blmid) to "base_and_survey.sde.pls_ptp_master_3857.blmid"

Is there anywhere else in the code that might be messed up because of this?

**Comment by clintonlunn** [comment]
@shodge17 I am trying to query the related features table for some sample data to work off of, but there only seems to be 1 value returned when try to return everything.

https://maps.freac.fsu.edu/arcgis/rest/services/LABINS/pls_master_to_ccr/MapServer/0/queryRelatedRecords?objectIds=1%3D1&relationshipId=0&outFields=*&definitionExpression=&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnZ=false&returnM=false&gdbVersion=&datumTransformation=&f=html

**Comment by shodge17** [comment]
Not sure what the issue is with your query above, but I think the problem the identify not finding things is simple.  Look at this line in script.js
    const layers = [countyBoundariesLayer, labinsLayer, ngsLayer, swfwmdLayer, CCCLLayer, townshipRangeSectionLayer];
Note that the newCCRLayer is not there at the end.  Change that line to this:
   const layers = [countyBoundariesLayer, labinsLayer, ngsLayer, swfwmdLayer, CCCLLayer, townshipRangeSectionLayer, newCCRLayer];
Now everything should work
Can you verify that and fix it if you agree

**Comment by clintonlunn** [comment]
@shodge17 maybe I'm misunderstanding the issue. I'm assuming that there is a related feature table somewhere that houses more CCR entries that are not represented on the main layers. Is that not the case?

**Comment by shodge17** [comment]
that is exactly right.  the separate service called pls_master_to_ccr has the exact same layer as the LABINS_Data service for the certified corner layer (pls_ptp_master_3857) but has the relationship class added

It might be possible to combine the two service, but I have not tried.  THe one in the main service currently has a join on it so we know which corners to color black (those with at least one ccr record).   That layer would have both a join and a relate if we combine them.  Just not sure that would work.  Could be a back burner issue

**Comment by clintonlunn** [comment]
```javascript
                  if (result.layerName === 'Certified Corners') {

                  // this is where we will query the related features  
                  const ccp_rquery = {
                    outFields: ["DOCNUM"],
                    relationshipId: 0,
                    objectIds: result["base_and_survey.sde.ccr_master.objectid"]
                  };
  
                  result.relatedFeatures = [];
                  await newCCRLayer.queryRelatedFeatures(ccp_rquery).then(async function (res) {
  
                    if (res[result.objectid]) {
                      res[result.objectid].features.forEach(async function (feature) {
                        await result.relatedFeatures.push(feature.attributes.docnum);
                      });
                    }
                  });
```

Looking through the identify logic here, it seems like we are relying on that related feature table from the newCCRLayer. If there is no data in it, how will we return any related features? 

It sounds like we need to accomplish a few things here:
* add the newCCRLayer in place of the LABINS_Data Certified Corners sublayer
* Symbolize those correctly if an image is present (seems to be already handled) 
* figure out which related features are associated with which objectid. (this is where i'm stuck at because there are (almost) no features in that related features table)

**Comment by shodge17** [comment]
You must have some old code in your branch.  If you find that code in master you will see the first line of the code is 
 if (result.layerName === 'base_and_survey.sde.pls_ptp_master_3857') {
The code should now be designed to skip any processing on the layer Certified Corners.  It is only there in the LABINS_Data service so we can color code the points as to which ones have ccrs

as to your points above
1) yes do this
2) already done in the LABINS_Data service
3) all the relate code is there and working correctly once you do #1 above.

**Comment by clintonlunn** [comment]
yeah that was pretty simple. my mistake, I was making a mountain out of nothing because I wasn't understanding the process. howver, it seems like the search bar is also broken as a result of these changes. Almost got it fixed on my local machine then test everywhere else in the app.

**Comment by shodge17** [comment]
1) the data zoom is now broken too (unless that is the one you mean).  Definitely because blmid needs to be base_and_survey.sde.pls_ptp_master_3857,blmid
2) when you make this change it can bring back more then one hit (remember blmids should be unique) because that layer now is in multiple services AND has a relate on it.
3) I know if you put 'limit 1' at the end of any SQL it will only bring back one record regardless of how many it should return.  This doesnt seem like a good solution because some of those queries you want more than one return.  
4) Right now I am wondering if the best solution would be to having a second copy pls_ptp_master_3857 in a  service with no joins or relates and just make sure it is called something different.  Problems will crop up all over the place with the name (see number 1 above) issue --  OR --  combine the two services into one and the pls_ptp layer has a join (for the symbolizing) and a relate (for the CCRs).  if we do that then the attribute would be back to just blmid. 

See what you think about this and if you think a conversation would help OR if you have other ideas let me know.

**Comment by clintonlunn** [comment]
It looks like the data zoom and search bar are both broken because they're expecting the old Certified Corners layer. If we make the related features query into a function, we can then call it from all of the other places (like the data query zoom panel, and search bar for example). I've got it mostly working on my local machine.

**Comment by shodge17** [comment]
Good to hear.  Here is another place where the join has messed things up with your search bar query for certified corner.
NOTE: all of the fields just need to be fully qualified as to where they come from.
sources: [{
      name: "Certified Corners",
      layer: new FeatureLayer({
        url: labinsLayer.findSublayerById(2).url,
        name: 'Certified Corners'
      }),
      **outFields: ["base_and_survey.sde.pls_ptp_master_3857.blmid",
                  "base_and_survey.sde.pls_ptp_master_3857.tile_name", 
                  "base_and_survey.sde.pls_ptp_master_3857.quad_num"
                ],
      searchFields: ["base_and_survey.sde.pls_ptp_master_3857.blmid", 
                    "base_and_survey.sde.pls_ptp_master_3857.tile_name", 
                    "base_and_survey.sde.pls_ptp_master_3857.quad_num"],
      suggestionTemplate: "BLMID: {base_and_survey.sde.pls_ptp_master_3857.blmid}<br>Quad: {base_and_survey.sde.pls_ptp_master_3857.tile_name}",**
      exactMatch: false,
      resultSymbol: highlightPoint,
      placeholder: "Search by Certified Corner",
    }, {

**Comment by clintonlunn** [comment]
I'm not sure if they need to be fully qualified, i seem to have found a way to not fully qualify everything. still testing though, will pick up again this evening

**Comment by shodge17** [comment]
Great!  I don't care how you solve it.  I will quit looking to "fix" things and just look for other possible code that is not working as a result of the join / relate.
