### ISSUE TITLE
Add additional coordinate conversion options

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#199]
Add "-ft" to the existing ones and "-mt" to the new ones

State Plane East meters 6437
State Plane west meters 6442
State Plane north meters 6440

these should NOT appear as default viewable -  User will need to add these if they want to see them

**Comment by clintonlunn** [comment]
Previous state for documentation purposes:
![image](https://user-images.githubusercontent.com/24685932/107367317-26eec200-6aad-11eb-8b20-599f670cb9ea.png)

**Comment by clintonlunn** [comment]
after addition: 
![image](https://user-images.githubusercontent.com/24685932/107370561-21937680-6ab1-11eb-9ec9-64a2efcba848.png)
