### ISSUE TITLE
Can not do an identify if the coordinate panel is displayed

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#200]
1) zoom in anywhere
2) open the coordinate panel
3) try and do an identify

Ideally you should be able to.  Let me know what you think about the work effort to allow this.  
If it is a lot of work I am going to be ok with having the use simply close that window before doing an identify.  No one is complaining about this so it has to be an easy fix before I want you to do anything about it.

**Comment by clintonlunn** [comment]
This is a limitation of the coordinate panel. The underlying logic is that the user cannot have the coordinate panel open or else it produces undesirable results (i.e. zooms to first result in identify). To avoid this clash in behavior, I disabled identify when user has this widget open.
