### ISSUE TITLE
Add the ability to close and open the Overview Map

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#201]

**Comment by clintonlunn** [comment]
is this different from the ability to show/hide the overview map? 

![image](https://user-images.githubusercontent.com/24685932/106916507-42388680-66d5-11eb-8844-577881f217ce.png)

**Comment by shodge17** [comment]
Got me again!  I know you have showed me this before....  I keep looking for a button on the overview itself.  Lets leave this be for now.
