### ISSUE TITLE
Favicon is not displaying 

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#207]
The icon is not displaying on the map browser tab.  
Here is what the code looks like:   <link rel="icon" href="/docs/images/favicon.png">
I think by removing the leading "/" the fix will happen.

**Comment by clintonlunn** [comment]
I believe this has more to do with how LABINS sits on the FREAC server. Could you post a screenshot of the directory structure of LABINS?

I think I'm able to see it, but I would need confirmation
![image](https://user-images.githubusercontent.com/24685932/110718045-3b22fd80-81d8-11eb-93e3-55e2b7ce1a00.png)


Also, It looks like the png isn't even on the server. Could you upload the png to the server and I'll do the correct reference once I can see it there?

**Comment by shodge17** [comment]
I put the icon on the server so all is good with this issue.
