### ISSUE TITLE
TRS section in Zoom To Feature panel not working

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#208]
The TRS Zoom to feature selection has stopped working, and it seems to be due to some CORS errors. 

![image](https://user-images.githubusercontent.com/24685932/110983186-71c35a00-8337-11eb-92e8-4f5b9f52485e.png)

![image](https://user-images.githubusercontent.com/24685932/110983263-89024780-8337-11eb-809b-34cf3017b02d.png)

**Comment by shodge17** [comment]
Aron fixed this. Security updates made the SQL statement look too suspicious and blocked it
