### ISSUE TITLE
search by polygon feature

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#214]

**Comment by clintonlunn** [comment]
this seems to be already implemented 
![image](https://user-images.githubusercontent.com/24685932/164370201-8b190a35-cedb-4521-a89a-663f6d2e28ac.png)

to reproduce:
- click on measurement widget button
- select area measurement tool
- draw your polygon (double click to finish drawing the polygon)
- click the identify ![image](https://user-images.githubusercontent.com/24685932/164370411-b15ed58e-6219-4f26-94bf-80b6ee3ffc94.png) button

**Comment by shodge17** [comment]
....Interesting.... Never knew this was there....
lets change the tool tip to read
Measurement Tools
(Select by area)

--IF-- you can change the tool tip for the measure area icon then make it read
Area measurement
Select Search area

**Comment by clintonlunn** [comment]
> ....Interesting.... Never knew this was there.... lets change the tool tip to read Measurement Tools (Select by area)
> 

So you would like it to say "Measurement Tools (Select by Area)"? 
i.e. 
![image](https://user-images.githubusercontent.com/24685932/165847319-2ef7a9a5-8129-44f3-96a4-efd1404b175d.png)
or would you like me to replace "Measurement Tools" with "Select by Area"
 
> --IF-- you can change the tool tip for the measure area icon then make it read Area measurement Select Search area
>
Like this? 
![image](https://user-images.githubusercontent.com/24685932/165847743-0103b3db-2c80-493d-9351-50ebb8a78e62.png)

**Comment by shodge17** [comment]
I think thats good

**Comment by clintonlunn** [comment]
Great, closing this issue then.
