### ISSUE TITLE
DEP access

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#218]
Users can log in using the public login (we must put those instructions in the map).

So basically this is just building a link to a document within the Oculus system. We have done this before

e. Coordinate a link for the 118 ECL features in the LABINS query panel to the appropriate scan/image file in the DEP Oculus Database on the webpage Implement login instruction for the DEP Oculus Database in the LABINS query panel (if direct linkage is approved by FDEP).

**Comment by shodge17** [comment]
This is complete
