### ISSUE TITLE
Information Panel/clear graphics

### ISSUE THREAD

**Issue by brenardfreac** [FREAC/LABINS#23]
When the 'zoom to' option is used and you get the gray box that shows the area, it is not intuitive as to how to make the box go away.  I saw the button for 'clear graphics' but this didn't register as the grey box to me.  (maybe a small note somewhere to point it out)

**Comment by clintonlunn** [comment]
potential solution:
- fade out on feature selection and highlight

**Comment by shodge17** [comment]
I think we should just leave this as is for now.  Lets see if we get any input from the users.
