### ISSUE TITLE
Tide Interpolation points that are blue just open the basic form

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#27]
If the attribute 
status_col = 1 (black)   then add a note that says "Non-tidal Call BSM @ 850-2452606
status_col = 2 (yellow) then the point has data, fill in the report as you are currently doing
status_col = 3 (blue)    then this point needs a study and open this page: http://www.labins.org/survey_data/water/FlexMap_docs/MHW_Procedures_wo_29_or_88_data_May_2009_with_checklist.pdf

**Comment by clintonlunn** [comment]
Download Approval Form links have been removed on the necessary fields.
