### ISSUE TITLE
Can you display the layer list and the legend at the same time

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#29]
Ideally the layer list and the legend could be displayed at the same time and could be movable.
Here is a link to something Clinton found that has potential for dragging the panels: 	https://www.w3schools.com/howto/howto_js_draggable.asp

**Comment by clintonlunn** [comment]
@shodge We are now able to display the layerlist and legend at the same time. Is this issue still relavent?

![image](https://user-images.githubusercontent.com/24685932/104400996-53043b00-5521-11eb-9f17-6c737d4cb03e.png)

**Comment by shodge17** [comment]
It is not.  closing
