### ISSUE TITLE
Add Bookmark Capability

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#34]
I know this is not part of 4.7 at this time.  I know it was part of 3.X so it should be there "soon."  Philip found this link that we can try if time permits:  https://community.esri.com/thread/205392-bookmark-in-arcgis-javascript-4x

**Comment by shodge17** [comment]
Looks like 4.8 has the bookmark widget!  https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Bookmarks.html

**Comment by clintonlunn** [comment]
This was integrated within pull request [here](https://github.com/FREAC/LABINS/pull/77).
