### ISSUE TITLE
Automatically switch to the identify panel when someone uses the data query option

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#51]
Example: Choose Tide layer to search
enter 8690 for the id
Hit "submit by ID"
the zoom to the station works.  It would be helpful to automatically change to the identify panel and show the results of the query.

**Comment by clintonlunn** [comment]
This should be fully functional now. You can now:
- search by ID or name within the same textbox
- panel toggles after the query happens
- feature is then zoomed to
