### ISSUE TITLE
Panel titles not always working when switching by buttons

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#55]
Sometimes the title of the panel will disappear if panels are switched by the button presses. 

![image](https://user-images.githubusercontent.com/24685932/40850640-301e0484-6593-11e8-994e-a4cfeee4dd91.png)

**Comment by PhilipGriffith** [comment]
Is this still an issue?

**Comment by clintonlunn** [comment]
This has been corrected, but another issue regarding that has come to light. Will create a new issue for it.
