### ISSUE TITLE
Identify needs to work off of visible only layers

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#57]
Right now we simply set the layers to be part of the identify.  The option to make it work off of only visible layers is not working with this release of the API (4.7) and ESRI knows it.  This is why the zoom to section identify is commented out now because it would identify things like GNIS within the section, but the GNIS layer was not turned on.  

There is a function in the code now called getVisibleLayerIds that works, but is currently only called during the initial map load -- NOT when the identify is called -- thats a problem.  

The only time our current strategy will look odd is when a user happens to click nears, say, a GNIS point while that layer is not turned on and the results come back and show the GNIS data.

**Comment by shodge17** [comment]
Look at issue #68 for how to deal with only visible layers.

**Comment by clintonlunn** [comment]
This has been completed and updated code can be found in the [MapCon](https://github.com/FREAC/LABINS/tree/MapCon) and [MapCon-ScrollableInfoPanel](https://github.com/FREAC/LABINS/tree/MapCon-ScrollableInfoPanel)
