### ISSUE TITLE
Zoom to section assumes there is only one piece per section

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#59]
08S 08W section 21 has two pieces.  Right now when you zoom to it, only one pieces is highlighted.
 
1) we should find the extent of both pieces.  (This is probably not necessary considering we zoom back out a bit after we find the section and the pieces will always be close enough not to require the find max extent of all pieces.

2) we need to highlight all pieces not just the first one which is currently being done.
The logic needed to do this should follow the same strategy that happens after you pick the range.

**Comment by clintonlunn** [comment]
This problem also happened in Zoom to Feature panel, when zooming to a county. Many of the counties consist of multi-polygons. Two thoughts: 

- If these polygons are unioned, they can be treated as a single geometry object and the existing zoom expansion can be preserved. If these are treated as a single geometry object, they will also be highlighted together. 

- Alternatively, these objects can be looped through to achieve the same results.

I am unsure of which method would perform fastest, but I think unioning the objects might be the most concise way of fixing this. It was the direction I wanted to go when initially writing the zoomToFeature function. Philip and I were trying to figure out why the geometryEngine would not work and ended up going the route of using for-loops. 

If wanted, I could probably fulfill this enhancement by Friday, or Monday at the latest.

**Comment by clintonlunn** [comment]
I think I was able to fix this within the zoom-to-section-multipolygon-fix branch. I will propose a pull request for review.  [Link](https://github.com/FREAC/LABINS/pull/60)

The steps that I took were as follows (These can also be seen on lines 556-572 of script.js) :
- Add geometries to a multiPolygonGeometries array
- Union multiPolygonGeometries array
- alter goTo() function to include the expand() method to zoom in less closely 
- Execute createBuffer() around the unioned geometries
