### ISSUE TITLE
Section names in Layer List

### ISSUE THREAD

**Issue by brenardfreac** [FREAC/LABINS#61]
When you open the layer list, there is labins data and control lines 3857.  The title of control lines 3857 should be something different that describes the layers in that section.

**Comment by clintonlunn** [comment]
This is because the title property of this layer has not been set. I checked the title of this layer in the current map version, and it is labeled "Other base layers". Should this title be used or perhaps another? This contains all of the polygon data for the LABINS map.

**Comment by brenardfreac** [comment]
Make it say the same thing as the older version - other base layers

Beverly
