### ISSUE TITLE
Data Query results

### ISSUE THREAD

**Issue by brenardfreac** [FREAC/LABINS#62]
If you choose Data Query for Erosion Control Lines, and choose a county that has no data, the result is all records for that data set.  This wasn't obvious to me when the list came up.  I chose Collier County and the first thing that popped up was Nassau County.  Maybe a message to say 'no records in that county'?

**Comment by clintonlunn** [comment]
This was happening because the submit button only looks at the textbox search. If the textbox is empty, then it will return everything (there is an sql 'like' query behind this).
