### ISSUE TITLE
Survey Benchmark question

### ISSUE THREAD

**Issue by brenardfreac** [FREAC/LABINS#64]
In the Data Query list, there is an option for 'Survey Benchmarks'.  There is no layer in the layer list called Survey Benchmarks, so it isn't clear what data this is - is this a separate data set or some version of other layers?  Also, R-monuments show up in the layer list but are available to query on - is there an explanation anywhere of what these are?

**Comment by clintonlunn** [comment]
I've changed the title of the Survey Benchmarks layer to make this connection more clear. 

R-Monuments: This sublayer is not available to query in the current labins map, so I did not include it in this map. If desired, I could add the capability to search on R-Monuments
