### ISSUE TITLE
The GNIS layer shows up in the identify results even though it is not turned on

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#68]
find a spot where a GNIS (Geographic Names) feature exists.  Turn off the layer.  Now do an identify where that feature is and you will see that the infopanel will have that feature in it.

I suspect this is true for other layers as well.  I think we just need an extra check on each layer in the identify to see if the layer is turned on or not before you see if any features are "near by"

**Comment by shodge17** [comment]
You can add the following to each of your queryInfoPanel if checks and the query will only report on visible layers:
if (results[i-1].attributes.layerName === 'USGS Quads' **&& results[i-1].feature.visible**

**Comment by clintonlunn** [comment]
Thanks!

**Comment by clintonlunn** [comment]
This does not seem to produced the desired effects. It seems that the visibility is not tied to the current visibility, but visibility on map load. 

I have been looking within the layers widget and it's possible to see the current visibility status of each layer that way.

**Comment by shodge17** [comment]
did you mean "...layers widget and it's **impossible** to see ..."?

**Comment by clintonlunn** [comment]
The layers widget has the different layers within children of the operationalItems attribute. For example, if looking at the layers widget to see visibility of 'USGS Quads' without making any changes after map load:

layersWidget.operationalItems.items[1].children.items[0].visible = **false**

If the visibility is changed (by pressing the on/off button within the map) and the layersWidget is checked again, the visibility will be displayed as: 

layersWidget.operationalItems.items[1].children.items[0].visible = **true**

**Comment by clintonlunn** [comment]
Working on a checkVisibility function that will update a list of visible layers by looking at the layerWidget each time the information panel is populated.

**Comment by clintonlunn** [comment]
This has been fixed in the [add-hires-imagery](https://github.com/FREAC/LABINS/tree/add-hires-images) and the [MapCon branch](https://github.com/FREAC/LABINS/tree/MapCon) branch has pulled this code to reflect those changes too.
