### ISSUE TITLE
Data query - Tide Stations

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#69]
Currently I think we show a complete 67 county list for the tide stations.  The stations only exist in about 37 or so counties.  Can you pair the list of counties to only those counties where stations exist?

**Comment by clintonlunn** [comment]
This has been completed. Changes are reflected [here](https://github.com/FREAC/LABINS/commit/674d391d78dbf5f908d75c5099b9e56b91ffd1a5) and within the [MapCon-ScrollableInfoPanel branch] (https://github.com/FREAC/LABINS/tree/MapCon-ScrollableInfoPanel)
