### ISSUE TITLE
Add CoordinateConversion widget

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#79]
Would it be possible to add the CoordinateConversion widget to LABINS as a test? The code is [here](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-CoordinateConversion.html).
The default format should be UTM and multiple conversions should be false.

**Comment by clintonlunn** [comment]
There are still too many coordinate systems present, (removing is proving to be difficult). 

This accomplishes adding, but not removing using the splice() method.

[Forum Link](https://community.esri.com/message/807203-re-49-coordinate-conversion-widget-adding-to-a-div?commentID=807203#comment-807203)

**Comment by PhilipGriffith** [comment]
Do you think we can close this issue?

**Comment by clintonlunn** [comment]
there Is still a bug in this, but it is not our fault. I’ll try to document this later today
