### ISSUE TITLE
Configure map to point to new services 

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#86]
Convert code to work with the new combined services and different county boundaries service. See email: 

The new service containing all of the data for the LABINS web application can now be found here:
[https://maps.freac.fsu.edu/arcgis/rest/services/LABINS/LABINS_Data/MapServer](https://maps.freac.fsu.edu/arcgis/rest/services/LABINS/LABINS_Data/MapServer)

As they’re used by multiple web applications, I’ve separated out the county boundaries and have put them here:
[https://maps.freac.fsu.edu/arcgis/rest/services/FREAC/County_Boundaries/MapServer](https://maps.freac.fsu.edu/arcgis/rest/services/FREAC/County_Boundaries/MapServer)
 
The CCCL service is hosted by FDEP and can be found here:
[https://ca.dep.state.fl.us/arcgis/rest/services/OpenData/COASTAL_ENV_PERM/MapServer/2/](https://ca.dep.state.fl.us/arcgis/rest/services/OpenData/COASTAL_ENV_PERM/MapServer/2/)

**Comment by PhilipGriffith** [comment]
Is this still an issue?
