### ISSUE TITLE
Change coordinate widget button symbol to "XY"

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#91]
Current map pin symbol is not very indicative of what the widget is:

- Change coordinate widget button symbol to "XY"

**Comment by clintonlunn** [comment]
This has not worked so far when trying to assign the expandIconClass to a textsymbol.

**Comment by shodge17** [comment]
It does not look like you can do this.  Even if you can, the icon appears again after you expand the widget and it would not look right in that case.  I say we close this issue for now unless someone complains.

**Comment by shodge17** [comment]
Closing
